/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedRanksRouteImport } from './routes/_authenticated/ranks'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRanksRoute = AuthenticatedRanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/create': typeof AuthenticatedCreateRoute
  '/home': typeof AuthenticatedHomeRoute
  '/me': typeof AuthenticatedMeRoute
  '/play': typeof AuthenticatedPlayRoute
  '/ranks': typeof AuthenticatedRanksRoute
  '/results': typeof AuthenticatedResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/create': typeof AuthenticatedCreateRoute
  '/home': typeof AuthenticatedHomeRoute
  '/me': typeof AuthenticatedMeRoute
  '/play': typeof AuthenticatedPlayRoute
  '/ranks': typeof AuthenticatedRanksRoute
  '/results': typeof AuthenticatedResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/ranks': typeof AuthenticatedRanksRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/browse'
    | '/create'
    | '/home'
    | '/me'
    | '/play'
    | '/ranks'
    | '/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/browse'
    | '/create'
    | '/home'
    | '/me'
    | '/play'
    | '/ranks'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/browse'
    | '/_authenticated/create'
    | '/_authenticated/home'
    | '/_authenticated/me'
    | '/_authenticated/play'
    | '/_authenticated/ranks'
    | '/_authenticated/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ranks': {
      id: '/_authenticated/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof AuthenticatedRanksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedRanksRoute: typeof AuthenticatedRanksRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedRanksRoute: AuthenticatedRanksRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
